PopulationCounter/Controllers/CrudMvcController.cs
using PopulationCounter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace PopulationCounter.Controllers
{
    public class CrudMvcController : Controller
    {
        HttpClient client = new HttpClient();
        // GET: CrudMvc
        public ActionResult Index()
        {
            List<Family> familyList = new List<Family>();
            client.BaseAddress = new Uri("https://localhost:44367/api/FirstApi");

            var response = client.GetAsync("FirstApi");
            response.Wait();

            var test = response.Result;

            if(test.IsSuccessStatusCode) // successStatusCode = 200
            {
                var display = test.Content.ReadAsAsync<List<Family>>();
                display.Wait();
                familyList = display.Result;
            }


            return View(familyList);
        }

        public ActionResult Details(int id)
        {
            Family f = null;
            client.BaseAddress = new Uri("https://localhost:44367/api/FirstApi");

            var response = client.GetAsync("FirstApi?id=" + id.ToString());
            response.Wait();

            var test = response.Result;

            if (test.IsSuccessStatusCode) // successStatusCode = 200
            {
                var display = test.Content.ReadAsAsync<Family>();
                display.Wait();
                f = display.Result;
            }
            return View(f);
        }

        // get details by pincode
        public ActionResult DetailsByPincode(int pin)
        {
            List<Family> familyListByPincode = new List<Family>();
            client.BaseAddress = new Uri("https://localhost:44367/api/SecondApi");

            var response = client.GetAsync("SecondApi?pin=" + pin.ToString());
            response.Wait();

            var test = response.Result;

            if (test.IsSuccessStatusCode) // successStatusCode = 200
            {
                var display = test.Content.ReadAsAsync<List<Family>>();
                display.Wait();
                familyListByPincode = display.Result;
            }

            return View(familyListByPincode);
        }

        // get details by village
        public ActionResult DetailsByVillage(string vil)
        {
            List<Family> familyListByPincode = new List<Family>();
            client.BaseAddress = new Uri("https://localhost:44367/api/SecondApi");

            var response = client.GetAsync("SecondApi?vil=" + vil);
            response.Wait();

            var test = response.Result;

            if (test.IsSuccessStatusCode) // successStatusCode = 200
            {
                var display = test.Content.ReadAsAsync<List<Family>>();
                display.Wait();
                familyListByPincode = display.Result;
            }

            return View(familyListByPincode);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Family fam)
        {
            client.BaseAddress = new Uri("https://localhost:44367/api/FirstApi");

            var response = client.PostAsJsonAsync<Family>("FirstApi",fam);
            response.Wait();

            var test = response.Result;

            if (test.IsSuccessStatusCode) // successStatusCode = 200
            {
                return RedirectToAction("Index");
            }

            return View("Create");
        }

        public ActionResult Edit(int id)
        {
            Family f = null;
            client.BaseAddress = new Uri("https://localhost:44367/api/FirstApi");

            var response = client.GetAsync("FirstApi?id=" + id.ToString());
            response.Wait();

            var test = response.Result;

            if (test.IsSuccessStatusCode) // successStatusCode = 200
            {
                var display = test.Content.ReadAsAsync<Family>();
                display.Wait();
                f = display.Result;
            }
            return View(f);
        }

        [HttpPost]
        public ActionResult Edit(Family f)
        {
            client.BaseAddress = new Uri("https://localhost:44367/api/FirstApi");

            var response = client.PutAsJsonAsync<Family>("FirstApi", f);
            response.Wait();

            var test = response.Result;

            if (test.IsSuccessStatusCode) // successStatusCode = 200
            {
                return RedirectToAction("Index");
            }

            return View("Edit");
        }

        public ActionResult Delete(int id)
        {
            Family f = null;
            client.BaseAddress = new Uri("https://localhost:44367/api/FirstApi");

            var response = client.GetAsync("FirstApi?id=" + id.ToString());
            response.Wait();

            var test = response.Result;

            if (test.IsSuccessStatusCode) // successStatusCode = 200
            {
                var display = test.Content.ReadAsAsync<Family>();
                display.Wait();
                f = display.Result;
            }
            return View(f);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            client.BaseAddress = new Uri("https://localhost:44367/api/FirstApi");

            var response = client.DeleteAsync("FirstApi/" + id.ToString());
            response.Wait();

            var test = response.Result;

            if (test.IsSuccessStatusCode) // successStatusCode = 200
            {
                return RedirectToAction("Index");
            }

            return View("Delete");
        }

        
    }
  
}

PopulationCounter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body style="background-image:url('../../images/vil2.jpg'); background-repeat:no-repeat; background-attachment:fixed; background-size:cover;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Population Counter", "Index", "CrudMvc", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "./CrudMvc/Index", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Pincode", "Index", "./CrudMvc/Index", new { area = "" }, new { @id = "PinId" })</li>
                    @*<li><a id="PinId">Pincode</a></li>*@
                    <li>@Html.ActionLink("Village", "Index", "./CrudMvc/Index", new { area = "" }, new { @id = "VilId" })</li>
                </ul>
            </div>
        </div>
    </div>

    <script>
        // For Pincode
        document.getElementById("PinId").onclick = function () { myFunction() }

        function myFunction() {
            let VlPin = prompt("Please enter pincode", "394110");

            if (VlPin.length == 6) {
                //alert("Valid pinode.");
                window.open("https://localhost:44367/CrudMvc/DetailsByPincode?pin=" + VlPin);
            }
            //else if (VlPin.length > 6) {
            //    alert("Invalid pinode.");
            //}
            else {
                alert("Please enter valid pinode.");
            }
        }

        // For Village
        document.getElementById("VilId").onclick = function () { myFunction1() }

        function myFunction1() {
            let Vlname = prompt("Please enter village name", "Jamankuva");

            if (Vlname.length > 0) {
                //alert("Valid pinode.");
                window.open("https://localhost:44367/CrudMvc/DetailsByVillage?vil=" + Vlname);
            }
            //else if (VlPin.length > 6) {
            //    alert("Invalid pinode.");
            //}
            else {
                alert("Please enter valid village name.");
            }
        }
    </script>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="color:white;">
            <p>Copyright &copy; @DateTime.Now.Year - All rights reserved. Population Counter.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>